apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: {{.Values.serviceName.db}}
spec:
  type: ClusterIP
  ports:
  - name: {{.Values.portName.db}}
    port: 5432
    targetPort: 5432
  selector:
    app: db
  
