apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: {{.Values.serviceName.redis}}
spec:
  type: ClusterIP
  ports:
  - name: {{.Values.portName.redis}}
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  
