apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: {{ .Release.Name}}-result-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: {{.Values.image.secondRepository}}
        name: result
        ports:
        - containerPort: 80
          name: result
