apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: {{ .Release.Name}}-voting-deployment
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: {{.Values.image.repository}}
        name: vote
        ports:
        - containerPort: 80
          name: vote
